extern crate cbindgen;

use std::env;
use std::path::PathBuf;

fn generate_c_headers() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let output_dir = PathBuf::from(&crate_dir).join("generated").join("include");
    std::fs::create_dir_all(&output_dir).expect("Failed to create generated/include directory");

    let header_path = output_dir.join("tlsnprover.h");

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_language(cbindgen::Language::Cxx)
        .with_namespace("tlsnprover")
        .with_header("/* TLSN TLSNotary FFI - Auto Generated */")
        .with_autogen_warning("/* Warning: Auto-generated by cbindgen. Do not modify manually. */")
        .with_include_guard("TLSNPROVER_H")
        .include_item("tlsn_init")
        .include_item("tlsn_cleanup")
        .include_item("tlsn_prove")
        .include_item("tlsn_verify")
        .include_item("tlsn_get_last_error")
        .include_item("tlsn_free_error_string")
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(header_path);
}

fn main() {
    // Tell Cargo that if the given file changes, to rerun this build script.
    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=src/ffi/mod.rs");

    // Platform-specific linking configuration
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap();
    match target_os.as_str() {
        "ios" => {
            println!("cargo:rustc-link-arg=-undefined");
            println!("cargo:rustc-link-arg=dynamic_lookup");
        }
        "android" => {
            println!("cargo:rustc-link-arg=-Wl,--allow-shlib-undefined");
        }
        _ => {}
    }

    // Only run cbindgen if not running cargo clippy
    if std::env::var("CARGO_CFG_CLIPPY").is_err() {
        generate_c_headers();
    }
}
