[target.aarch64-linux-android]
runner = "cargo ndk-runner"

[target.armv7-linux-androideabi]
runner = "cargo ndk-runner"

[target.i686-linux-android]
runner = "cargo ndk-runner"

[target.x86_64-linux-android]
runner = "cargo ndk-runner"
