/* TLSN TLSNotary FFI - Auto Generated */

#ifndef TLSN_FFI_H
#define TLSN_FFI_H

/* Warning: Auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

int32_t tlsn_init(void);

void tlsn_cleanup(void);

int32_t tlsn_prove(int32_t mode,
                   int32_t provider,
                   const char *transaction_id,
                   const char *profile_id,
                   const char *cookie,
                   const char *access_token);

int32_t tlsn_verify(int32_t provider, const char *transaction_id);

const char *tlsn_get_last_error(void);

void tlsn_free_error_string(char *ptr);

#endif  /* TLSN_FFI_H */
