/* ZKP2P TLSNotary FFI - Auto Generated */

#ifndef ZKP2P_FFI_H
#define ZKP2P_FFI_H

/* Warning: Auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

int32_t zkp2p_init(void);

void zkp2p_cleanup(void);

int32_t zkp2p_prove(int32_t mode,
                    int32_t provider,
                    const char *transaction_id,
                    const char *profile_id,
                    const char *cookie,
                    const char *access_token);

int32_t zkp2p_verify(int32_t provider, const char *transaction_id);

const char *zkp2p_get_last_error(void);

void zkp2p_free_error_string(char *ptr);

#endif  /* ZKP2P_FFI_H */
